<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Boilerplate.Modules.Tickets</RootNamespace>
		<AssemblyName>Boilerplate.Modules.Tickets</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Boilerplate.BuildingBlocks.Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Boilerplate.BuildingBlocks.Web.csproj" />
		<ProjectReference Include="..\Modules.Tickets.Contracts\Boilerplate.Modules.Tickets.Contracts.csproj" />
	</ItemGroup>

</Project>
