<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Boilerplate.BuildingBlocks.Quota</RootNamespace>
		<AssemblyName>Boilerplate.BuildingBlocks.Quota</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Finbuckle.MultiTenant" />
		<PackageReference Include="Finbuckle.MultiTenant.Abstractions" />
		<PackageReference Include="StackExchange.Redis" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Boilerplate.BuildingBlocks.Core.csproj" />
		<ProjectReference Include="..\Shared\Boilerplate.BuildingBlocks.Shared.csproj" />
	</ItemGroup>

</Project>
