<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Boilerplate.Modules.Chat</RootNamespace>
		<AssemblyName>Boilerplate.Modules.Chat</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;CA1002;CA2227;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Boilerplate.BuildingBlocks.Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Boilerplate.BuildingBlocks.Web.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Eventing\Boilerplate.BuildingBlocks.Eventing.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Storage\Boilerplate.BuildingBlocks.Storage.csproj" />
		<ProjectReference Include="..\Modules.Chat.Contracts\Boilerplate.Modules.Chat.Contracts.csproj" />
		<ProjectReference Include="..\..\Files\Modules.Files.Contracts\Boilerplate.Modules.Files.Contracts.csproj" />
		<ProjectReference Include="..\..\Identity\Modules.Identity.Contracts\Boilerplate.Modules.Identity.Contracts.csproj" />
	</ItemGroup>

</Project>
