<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
	    <RootNamespace>Boilerplate.BuildingBlocks.Core</RootNamespace>
	    <AssemblyName>Boilerplate.BuildingBlocks.Core</AssemblyName>
    </PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Mediator.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

</Project>
