#!/usr/bin/env bash
# Export the API's OpenAPI document to the checked-in contract (ADR-0004).
#
#   bash scripts/export-openapi.sh              # writes clients/openapi/v1.json
#   bash scripts/export-openapi.sh path/to.json # or somewhere else
#
# The document is generated by the API host itself, started with `--export-openapi`
# (see src/Host/Boilerplate.Api/OpenApiDocumentExport.cs): it maps the module
# endpoints, serialises the document and exits without running the middleware
# pipeline. NO DATABASE, cache, mail server or object store is contacted, which is
# what lets the drift gate re-run this on a bare CI runner.
#
# Two settings are forced here rather than left to whatever the machine has:
#
#   ASPNETCORE_ENVIRONMENT=OpenApiExport — deliberately neither Development (whose
#     ValidateOnBuild would demand the background-job services the export turns
#     off) nor Production (whose configuration guard demands real secrets). Only
#     appsettings.json is loaded, so the document never depends on a developer's
#     local overrides.
#   OpenApiOptions__Enabled=true — appsettings.Production.json ships the document
#     endpoint off; the exporter needs the OpenAPI services registered regardless.
#
# The output is normalised (keys sorted recursively, two-space indent, trailing
# newline) so the artifact is byte-identical across runs, machines and endpoint
# registration order — a re-run must leave `git status` clean.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OUTPUT=${1:-clients/openapi/v1.json}
DOCUMENT=${OPENAPI_DOCUMENT:-v1}
CONFIGURATION=${CONFIGURATION:-Release}

command -v python3 >/dev/null || {
  echo "export-openapi.sh: python3 is required to normalise the document." >&2
  exit 1
}

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

ASPNETCORE_ENVIRONMENT=OpenApiExport \
DOTNET_ENVIRONMENT=OpenApiExport \
OpenApiOptions__Enabled=true \
dotnet run --project src/Host/Boilerplate.Api --no-launch-profile -c "$CONFIGURATION" -- \
  --export-openapi "$tmp_dir/raw.json" --openapi-document "$DOCUMENT"

mkdir -p "$(dirname "$OUTPUT")"
python3 - "$tmp_dir/raw.json" "$OUTPUT" <<'PY'
import json, sys

source, target = sys.argv[1], sys.argv[2]
with open(source, encoding="utf-8") as handle:
    document = json.load(handle)

# Object key order carries no meaning in OpenAPI, but ASP.NET Core emits paths and
# schemas in endpoint-discovery order — which reflection can reshuffle between
# runs. Sorting every object makes the artifact a function of the API alone.
# Arrays (required, enum, parameters, …) are left exactly as generated.
with open(target, "w", encoding="utf-8") as handle:
    json.dump(document, handle, indent=2, sort_keys=True, ensure_ascii=False)
    handle.write("\n")
PY

echo "OpenAPI document written to $OUTPUT"
