#!/usr/bin/env bash
# Generate the .env that the local docker-compose stack needs (issue #17). The containers run as
# Production, so ProductionConfigurationGuard rejects any secret that looks like a template
# placeholder — which is why docker-compose.yml ships no default for these four and this script
# makes real ones instead. .env is gitignored; nothing generated here is ever committed.
#
#   bash scripts/local-env.sh              # create .env, keep an existing one
#   bash scripts/local-env.sh --force      # regenerate every secret
#
# Sibling of scripts/dev-secrets.sh, which does the same job for `dotnet run` via user-secrets.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

ENV_FILE=".env"

if [ -f "$ENV_FILE" ] && [ "${1:-}" != "--force" ]; then
  echo "$ENV_FILE already exists — keeping it. Re-run with --force to regenerate the secrets."
  exit 0
fi

# Alphanumeric-only output: these values land in a Postgres connection string and a MinIO URL,
# where '/', '+', '=' and ':' would need escaping.
rand() {
  LC_ALL=C openssl rand -base64 "$1" | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c "1-$2"
}

# The seeded admin password must satisfy the Identity policy: 10+ characters with an upper, a
# lower and a digit. The suffix guarantees all three regardless of what the random core drew.
SEED_ADMIN_PASSWORD="$(rand 24 20)Aa1"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/local-env.sh — local development only, never committed.
# Regenerate with: bash scripts/local-env.sh --force
#
# Only the secrets live here. Every other setting (ports, URLs, database and bucket names) has a
# default in docker-compose.yml; see .env.example for the full list and override what you like.

POSTGRES_PASSWORD=$(rand 24 32)
MINIO_ROOT_PASSWORD=$(rand 24 32)
JWT_SIGNING_KEY=$(rand 48 64)
SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE with freshly generated secrets."
echo
echo "  docker compose up --build"
echo "  curl -fsS http://localhost:8080/health/ready"
echo
echo "Sign in to the console at http://localhost:8081 as admin@root.com;"
echo "the password is SEED_ADMIN_PASSWORD in $ENV_FILE."
