<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Boilerplate.Modules.Webhooks.Contracts</RootNamespace>
    <AssemblyName>Boilerplate.Modules.Webhooks.Contracts</AssemblyName>
    <NoWarn>$(NoWarn);CA1054;CA1056;S2094</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Boilerplate.BuildingBlocks.Shared.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Core\Boilerplate.BuildingBlocks.Core.csproj" />
  </ItemGroup>
</Project>
